### ISSUE TITLE
Mod not functional

### ISSUE THREAD

**Issue by AHartTN** [lazyMods/RandomFluidCows#2]
[17:46:11] [Server thread/WARN]: Failed to create mob
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(net.minecraft.world.entity.ai.attributes.Attribute)" because "this.f_22141_" is null
        at net.minecraft.world.entity.ai.attributes.AttributeMap.m_22181_(AttributeMap.java:62) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.LivingEntity.m_21133_(LivingEntity.java:1810) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.LivingEntity.m_21233_(LivingEntity.java:1575) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:230) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.Mob.<init>(Mob.java:116) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:14) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.AgeableMob.<init>(AgeableMob.java:28) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.animal.Animal.<init>(Animal.java:40) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.entity.animal.Cow.<init>(Cow.java:35) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at lazy.moofluids.entity.MooFluidEntity.<init>(MooFluidEntity.java:49) ~[MooFluids-1.18-1.2.0.jar%23351!:1.18-1.2.0]
        at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:458) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:239) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:175) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23557!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by lazynessmind** [comment]
HI. Can you provide me with the mod list, minecraft version and forge version pls.
